{"name": "test_user_login_failure_incorrect_credentials", "status": "passed", "steps": [{"name": "User Login: Login Failure (Incorrect Credentials)", "status": "passed", "attachments": [{"name": "login_failure_screenshot", "source": "33ea790c-200e-46b4-ae73-5fd714386360-attachment.png", "type": "image/png"}], "start": 1697059257261, "stop": 1697059259265}], "start": 1697059257261, "stop": 1697059259265, "uuid": "26ef34f4-1c44-4f6b-baeb-4b6c4b5c8fc5", "historyId": "859081d5955c0abca614e5d1a31c42be", "testCaseId": "859081d5955c0abca614e5d1a31c42be", "fullName": "allure_report.test.TestUserLogin#test_user_login_failure_incorrect_credentials", "labels": [{"name": "story", "value": "User Login"}, {"name": "parentSuite", "value": "allure_report"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "PRINCE"}, {"name": "thread", "value": "20500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure_report.test"}]}