{"name": "test_user_profile_update_failure_invalid_data", "status": "passed", "steps": [{"name": "User Profile Update: Update Failure (Invalid Data)", "status": "passed", "attachments": [{"name": "profile_update_failure_screenshot", "source": "eeb21eb5-e454-4872-8116-0d272ba8f4f8-attachment.png", "type": "image/png"}], "start": 1697059286171, "stop": 1697059305564}], "start": 1697059286171, "stop": 1697059305564, "uuid": "726849ff-b5ad-466d-b160-374836a8757f", "historyId": "5e5dfb1fe6b10771881e50173911d895", "testCaseId": "5e5dfb1fe6b10771881e50173911d895", "fullName": "allure_report.test.TestUserProfileUpdate#test_user_profile_update_failure_invalid_data", "labels": [{"name": "story", "value": "User Profile Update"}, {"name": "parentSuite", "value": "allure_report"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "TestUserProfileUpdate"}, {"name": "host", "value": "PRINCE"}, {"name": "thread", "value": "20500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure_report.test"}]}